# Project information
site_name: Ciencias del Significado
# site_url: https://squidfunk.github.io/mkdocs-material/
site_author: Valmore Agelvis
site_description: >-
  Fichero sobre Ciencias del Significado del profesor Dr. Valmore Agelvis

# Copyright
copyright: Copyright &copy; 2021 Valmore y Matias Agelvis.


theme:
  name: material
  custom_dir: overrides
  language: es
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Tema Diurno 
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Tema Nocturno
  favicon: images/dualbook.png
  icon:
    logo: material/book-open

extra:
  social:
    - icon: fontawesome/brands/medium
      link: https://medium.com/@valmore.agelvis
    - icon: fontawesome/solid/paper-plane
      link: mailto:agelvis@ula.ve

# plugins:
#   - search
#   - pdf-export

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra_css:
  - stylesheets/extra.css